import pygame as py

class instructions():

    # method to display the ui of the game instructions page
    def instructionsui(self,screen):
        screen.fill((100, 100, 100))
        exitfont = py.font.Font(None, 80)
        normalfont = py.font.Font(None, 30)
        otherfont = py.font.Font(None, 50)
        exitbutton = exitfont.render("X", False, (0, 0, 0))
        titlebox = py.Rect((0, 0), (600, 75))
        exitbox = py.Rect((530, 10), (50, 50))
        text1 = normalfont.render("LEFT AND RIGHT ARROWS", False, (0, 0, 0))
        screen.blit(text1, (17, 90))
        text2 = normalfont.render("DOWN ARROW", False, (0, 0, 0))
        screen.blit(text2, (81, 130))
        text3 = normalfont.render("UP ARROW", False, (0, 0, 0))
        screen.blit(text3, (95, 170))
        text4 = normalfont.render("SPACE", False, (0, 0, 0))
        screen.blit(text4, (117, 210))
        text5 = normalfont.render("C", False, (0, 0, 0))
        screen.blit(text5, (143, 250))
        text6 = normalfont.render("Z", False, (0, 0, 0))
        screen.blit(text6, (143, 290))
        dsc1 = normalfont.render("Move left and right", False, (0, 0, 0))
        screen.blit(dsc1, (355, 90))
        dsc2 = normalfont.render("Speed up block", False, (0, 0, 0))
        screen.blit(dsc2, (370, 130))
        dsc3 = normalfont.render("Rotate clockwise", False, (0, 0, 0))
        screen.blit(dsc3, (361, 170))
        dsc4 = normalfont.render("Hard drop", False, (0, 0, 0))
        screen.blit(dsc4, (399, 210))
        dsc5 = normalfont.render("Hold", False, (0, 0, 0))
        screen.blit(dsc5, (424, 250))
        dsc6 = normalfont.render("Rotate counterclockwise", False, (0, 0, 0))
        screen.blit(dsc6, (330, 290))
        headertextinstr = otherfont.render("GAME INSTRUCTIONS", False, (0, 0, 0))
        screen.blit(headertextinstr, (115, 25))
        screen.blit(exitbutton, (535, 10))
        py.draw.rect(screen, (0, 0, 0), titlebox, width=1)
        py.draw.rect(screen, (0, 0, 0), exitbox, width=1)
        return exitbox